[package]
name = "barnacle-gui"
version.workspace = true
edition.workspace = true
homepage.workspace = true

[dependencies]
barnacle-lib = { path = "../barnacle-lib" }
iced = "0.13.1"

[features]
default = ["debug"]
debug = ["iced/debug"]
